# in _config.yml
title: "Data Pre-Processing and Visualization OER"
description: "An OER for Data Pre-processing and Visualization developed Spring 2022 at East Central University"
logo: JuliaSetECUColors.jpg
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/nurfnick/Data_Viz
html:
  use_repository_button: true
  use_issues_button: true
launch_buttons:
  colab_url: "https://colab.research.google.com"
